# Generated by Django 2.1.7 on 2019-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unq',
            field=models.IntegerField(unique=True),
        ),
    ]
