# Generated by Django 2.1.7 on 2019-08-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_case',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_task',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
