# Generated by Django 2.1.7 on 2019-08-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_input1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input1',
            name='csvfile1',
            field=models.FileField(upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='csvfile2',
            field=models.FileField(upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='file1',
            field=models.FileField(upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='file2',
            field=models.FileField(upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='file3',
            field=models.FileField(upload_to='templates'),
        ),
    ]
