# Generated by Django 2.1.7 on 2019-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20190824_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input1',
            name='file3',
        ),
        migrations.AlterField(
            model_name='input1',
            name='csvfile1',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='csvfile2',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='file1',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='input1',
            name='file2',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
