# Generated by Django 2.1.7 on 2019-08-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20190824_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq', models.IntegerField(unique=True)),
                ('file1', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('file2', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('csvfile1', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('csvfile2', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Input1',
        ),
    ]
