# Generated by Django 2.1.7 on 2019-08-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20190825_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='csvfile2',
            new_name='audio1',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='document',
            name='url2',
        ),
    ]
